// Type for the module generated by vite-plugin-content.ts.
declare module 'virtual:content' {
  import type { Scenario, Track } from './schema/scenario.ts'
  import type { Challenge } from './schema/challenge.ts'
  const content: { tracks: Track[]; scenarios: Scenario[]; challenges: Challenge[] }
  export default content
}
