// Types for the modules generated by vite-plugin-content.ts.
// (An ambient module can't use relative `import` declarations, so types come
// in through import() type expressions.)
declare module 'virtual:content' {
  export type Item = import('./content/item.ts').Item
  export type MultiChallenge = import('./content/item.ts').MultiChallenge

  // The index: everything the queue, skill tree and unlocks need.
  const content: { tracks: import('./schema/scenario.ts').Track[]; items: import('./screens/HomeScreen.tsx').QueueItem[] }
  export default content
  // One item's full content, loaded on demand as its own chunk.
  export function loadItem(id: string): Promise<Item>
}
