// Type for the module generated by vite-plugin-content.ts.
declare module 'virtual:content' {
  import type { Scenario, Track } from './schema/scenario.ts'
  const content: { tracks: Track[]; scenarios: Scenario[] }
  export default content
}
